# Generated by Django 4.1.7 on 2023-04-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='working_mode',
            field=models.TextField(blank=True, verbose_name='Режим работы'),
        ),
    ]
