# Generated by Django 4.1.7 on 2023-04-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_service', models.CharField(max_length=550)),
                ('delivery_time', models.CharField(max_length=150)),
                ('cost_of_delivery', models.CharField(max_length=100)),
                ('delivery_country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.TextField()),
                ('bank_card', models.TextField()),
                ('cashless_payments', models.TextField()),
            ],
        ),
    ]
