# Generated by Django 4.1.7 on 2023-04-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_card_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cash_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CashlessPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cashless_pay_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cost_of_delivery',
            field=models.CharField(max_length=100, verbose_name='Соймость'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_country',
            field=models.TextField(verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_service',
            field=models.CharField(max_length=550, verbose_name='Служба доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.CharField(max_length=150, verbose_name='Срок'),
        ),
    ]
