# Generated by Django 4.1.7 on 2023-04-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_payment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='image',
        ),
    ]
