# Generated by Django 4.1.7 on 2023-03-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('image', models.FileField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='ColorAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('options', models.CharField(max_length=500, verbose_name='Параметры')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Вес')),
                ('material', models.CharField(max_length=400, verbose_name='Материал')),
                ('coverage', models.CharField(blank=True, max_length=400, verbose_name='Покрытие')),
                ('equipment', models.CharField(blank=True, max_length=1000, verbose_name='Комплектация')),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('color', models.ManyToManyField(to='catalog.colorall')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
