# Generated by Django 4.1.7 on 2023-03-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorall',
            name='number',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
