# Generated by Django 4.1.7 on 2023-04-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_slug_category_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='catalog/static/image/'),
        ),
    ]
