# Generated by Django 4.1.7 on 2023-05-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorall',
            name='number',
        ),
    ]
