# Generated by Django 4.1.7 on 2023-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_color_delete_colorall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors_product', models.CharField(max_length=100, verbose_name='Цвет')),
                ('number_colors', models.CharField(max_length=100, verbose_name='Номер цвета')),
            ],
        ),
    ]
