# Generated by Django 4.1.7 on 2023-05-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_color_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='number_colors',
        ),
    ]
