# Generated by Django 4.1.7 on 2023-05-30 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_delivery_cost_of_delivery_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='доставка')),
                ('delivery_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='служба доставки')),
                ('payment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.payment', verbose_name='способ оплаты')),
            ],
        ),
    ]
