# Generated by Django 4.1.7 on 2023-05-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderproduct_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.orderdelivery', verbose_name='доставка'),
        ),
    ]
