# Generated by Django 4.1.7 on 2023-05-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='delivery',
        ),
    ]
