# Generated by Django 4.1.7 on 2023-05-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_delivery_cost_of_delivery_and_more'),
        ('orders', '0007_alter_orderdelivery_delivery_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='служба доставки'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='payment_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.payment', verbose_name='способ оплаты'),
        ),
    ]
