# Generated by Django 4.1.7 on 2023-05-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderdelivery_delivery_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.orderdelivery', verbose_name='доставка'),
        ),
    ]
