# Generated by Django 4.1.7 on 2023-05-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderproduct_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='OrderDelivery',
        ),
    ]
